
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 25 15:01:41 EDT 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A4Symbol {
  /* terminals */
  public static final int TIMES = 23;
  public static final int READ = 13;
  public static final int ELSE = 26;
  public static final int SEMICOLON = 16;
  public static final int PLUS = 21;
  public static final int RPAREN = 9;
  public static final int INT = 5;
  public static final int DIGIT = 27;
  public static final int FSTOP = 19;
  public static final int END = 7;
  public static final int RETURN = 11;
  public static final int IDENTIFIER = 2;
  public static final int TRUE = 29;
  public static final int IF = 12;
  public static final int LPAREN = 8;
  public static final int WRITE = 14;
  public static final int BEGIN = 6;
  public static final int NOTEQUALS = 25;
  public static final int EQUALS = 24;
  public static final int STRING = 3;
  public static final int COMMA = 15;
  public static final int EOF = 0;
  public static final int DIVIDE = 22;
  public static final int MAIN = 10;
  public static final int FALSE = 28;
  public static final int MINUS = 20;
  public static final int error = 1;
  public static final int ASSIGN = 17;
  public static final int QSTRING = 18;
  public static final int REAL = 4;
}

